### ISSUE TITLE
Support FireFox using WebExtensions API ?

### ISSUE THREAD

**Issue by asimen1** [asimen1/chrome-ext-messenger#5]
FireFox 54 has cross-browser compatible extensions using the WebExtensions API.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions

**Comment by AleksandarDev** [comment]
I need this feature but for all browsers (Firefox, Opera, Edge and Safari). The Safari is not that easy, but others should be PnP using WebExtension's `browser` API. 

Have you done any work on this? If not, can I take this task?

**Comment by asimen1** [comment]
Hi @AleksandarDev,
Sorry for the late response.

I haven't started any work on this so feel free to take this task.
If you need any help understanding the code, don't hesitate to contact me,

I would pay special attention to the [getCurrentExtensionPart](https://github.com/asimen1/chrome-ext-messenger/blob/4dd0789f3360d4165a54c7357af8a3e3cd3cfc96/src/utils.js#L69) method and the [MockPort](https://github.com/asimen1/chrome-ext-messenger/blob/4dd0789f3360d4165a54c7357af8a3e3cd3cfc96/src/mockPort.js#L3) class.

Also, if the code between WebExtension API and Safari API differs alot I would consider making a `ConnectionFactory` class that will initiate the proper connection (i.e. `WEConnection` & `SafariConnection` which both inherit the same `BaseConnection` class for common code).

**Comment by AleksandarDev** [comment]
Thanks. Will update you on the progress. 

The Safari, as far as I've seen seen, doesn't have long lasting connection (eg. port's) only short lived messages which can basically wait before calling the response callback (where Chrome disposes the short lived messages if they don't respond quickly). But that should be no problem to integrate either.

**Comment by asimen1** [comment]
I see.

Maybe you can try abstracting the `Port` object, having a single behavior for both cases.
Meaning, if you can implement/simulate long lived connections (ports) using Safari's single messages then most of the library code won't change, only the port creation part.

Of course, I haven't researched or looked in Safari's docs at all so don't take what I say as a concrete suggestion, just a theory :smile:

**Comment by Jarred-Sumner** [comment]
https://github.com/Jarred-Sumner/chrome-ext-messenger

I forked this and have a branch that _seems_ to work with WebExtension via https://github.com/mozilla/webextension-polyfill

I've only tested it in Chrome though...once I get rest of this extension working via that polyfill, I'll test the whole thing in Firefox. The point of that polyfill is to be as compatible with WebExtension API as possible though, so theoretically if it works from the polyfill, it _should_ work on Firefox too.

Totally up to you though if you're comfortable including a polyfill as a dependency in this library. For my use, I don't mind because I'm going to use the polyfill anyway, however whether or not it should be in a library is a decision

**Comment by asimen1** [comment]
Hey @Jarred-Sumner 
Thanks for posting!

Overall this looks like a good direction (a polyfill solution sounds great to me).
However, tried testing it and I get an error that seems to originate from the importing of the webextension-polyfill package.

![image](https://user-images.githubusercontent.com/12048798/43778269-e1993aea-9a5d-11e8-8aaa-c09fe237a722.png)

![image](https://user-images.githubusercontent.com/12048798/43778344-1ee20a8a-9a5e-11e8-92e6-5f29911a0c61.png)

Do you have any idea what can cause this?
(Didn't tested it on Firefox as well).

I will open an issue for them if you don't have any other suggestion...

**Comment by asimen1** [comment]
Hi @Jarred-Sumner,

I did some research and apparently there is no need for the 'browser' polyfill package since this library already supports Firefox add-ons!

Turns out Firefox implements the chrome namespace and all its API too allow easy migration of chrome extensions to Firefox. You can read more about it [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities#Firefox_supports_both_chrome_and_browser_namespaces), [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API) and [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension).

Made some testing in a Firefox add-on and everything seems to work as expected.

So, I've created a new package [ext-messenger](https://www.npmjs.com/package/ext-messenger) (and deprecated 'chrome-ext-messenger').
Please use it instead since this package will no longer be maintained.

Thanks,
Asaf.
