### ISSUE TITLE
Rejecting sendMessage when connection doesn't exist

### ISSUE THREAD

**Issue by AleksandarDev** [asimen1/chrome-ext-messenger#7]
I noticed that when connection is not longer valid, sending a message hangs my requests because they are never resolved nor rejected.

I get this message, 
https://github.com/asimen1/chrome-ext-messenger/blob/master/src/connection.js#L336

Shouldn't this also reject the sendMessage promise?

**Comment by asimen1** [comment]
Hi @AleksandarDev,

Thanks for the issue, your suggestion sounds like a good idea.
I will try to add it in the next days.

**Comment by asimen1** [comment]
New version 2.0.12 released with this change (published to [npm](https://www.npmjs.com/package/chrome-ext-messenger)).
Enjoy :)

**Comment by AleksandarDev** [comment]
Thanks. 😄
