### ISSUE TITLE
chrome.runtime = undefined in Lastest Chrome Update 66

### ISSUE THREAD

**Issue by evan111** [asimen1/chrome-ext-messenger#8]
## Connection fails in Chrome Version 66.0.3359.139 (Official Build) (64-bit)
**Connection has been working in previous versions of chrome 65 builds.**

**Description**
Cannot make connection between extension and background page due to failure with the following exception

Code line:
`
this._port = this._myExtPart === Constants.BACKGROUND ? new MockPort({ name: this._myName }) : chrome.runtime.connect({ name: this._myName });
`
Reason: chrome.runtime is undefnied

`TypeError: Cannot read property 'connect' of undefined
    at Connection.<anonymous> (chrome-ext-messenger.min.js:1372)
    at Connection._init (chrome-ext-messenger.min.js:1413)
    at Connection.<anonymous> (chrome-ext-messenger.min.js:460)
    at new Connection (chrome-ext-messenger.min.js:1342)
    at Messenger.initConnection (chrome-ext-messenger.min.js:116)
    at Messenger.<anonymous> (chrome-ext-messenger.min.js:460)
    at ChromeProtocolMessengerFactory.webpackJsonp../src/app/services/chromeprotocol/messenger/chrome.protocol.messenger.factory.ts.ChromeProtocolMessengerFactory.createConnection (chrome.protocol.messenger.factory.ts:22)
    at new ChromeProtocolDebugger (chrome.protocol.debugger.ts:21)
    at resolveToken (core.js:1296)
    at tryResolveToken (core.js:1242)`

**Comment by asimen1** [comment]
Hi @evan111 ,

I can't seem to reproduce the issue (using the same Chrome version)...
Its far fetched that this API is no longer available since 'runtime' is a basic API that many extensions use, so Im guessing its probably something else...

Can you give me some additional info?
- At what extension part are you trying to init the connection? content script, popup, devtool ?
- On which url did this happen to you?
- Is your extension published or its code available to look at ?

**Comment by evan111** [comment]
Hi Asaf,

Thanks for the response.

Devtools extension -> Background page.

Yes it's surprised me too being chrome.runtime api. I have a bitbucket account where the code is. If you give me your email address I can give you access, you can load it and it will reproduce on any site my devtool extension loads for.

Rolling back to chrome 65 works fine and has been working fine for the past 6 months.

email me at evan@evanhegyi.com.

Cheers,

Evan

**Comment by evan111** [comment]
Thanks,

Asaf helped me out, and discovered that I had "sand boxed" index.html in the manifest.json file. This was working in in chrome 65, which it probably should not have been, and caught me out after the 66 update.

All works now.

He also pointed me to a miss understanding of my use of his messaging library.

Thanks for your help!

Cheers,

Evan

**Comment by asimen1** [comment]
No problem, got to learn about sandboxing on the way :)
Thanks for the good words.
